# Generated by Django 2.2.6 on 2019-10-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='comment',
        ),
    ]
